# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_fixedform"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John S. Urban"
description = ""
categories = [""]
keywords = ["fortran", "fortran-package-manager"]
homepage = "https://github.com/janedoe/M_fixedform"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
# new default with v0.8.0
# force module naming rules to avoid collisions with other packages
#module-naming = true
# traditional where user can use any module name
module-naming = false

# new section with v0.8.0
[fortran]
#implicit-typing = false
#implicit-external = false
#source-form = "free"
# traditional pre-version8 compatibility
implicit-typing = true
implicit-external = true
source-form = "default"

[install]
library = false

# example
#[[test]]
#name="runTests"
#source-dir="test"
#main="test_suite_easy.f90"
#[test.dependencies]
##M_framework = { git = "https://github.com/urbanjost/M_framework.git" }

[dev-dependencies]
M_framework  =  {  git  =  "https://github.com/urbanjost/M_framework.git"  }
M_ncurses    =  {  git  =  "https://github.com/urbanjost/M_ncurses.git"    }
M_kracken    =  {  git  =  "https://github.com/urbanjost/M_kracken.git"    }
M_time       =  {  git  =  "https://github.com/urbanjost/M_time.git"       }
